### PR TITLE
Various fixes

### LINKED ISSUE #3: Whitelist test fails
Running the test suite with a fresh clone currently outputs:

```bash
$ npm test

> third-party-resources-checker@0.0.1 test [...]/third-party-resources-checker
> mocha

  ․․․․․․․․․

  8 passing (2s)
  1 failing

  1) Starting test suite should ignores whitelisted 3rd party url:

      Uncaught Error: expected [ 'http://example.org/' ] to sort of equal []
      + expected - actual

      +[]
      -[
      -  "http://example.org/"
      -]
      
      at Assertion.assert ([...]/third-party-resources-checker/node_modules/expect.js/index.js:96:13)
      at Assertion.eql ([...]/third-party-resources-checker/node_modules/expect.js/index.js:230:10)
      at ChildProcess.<anonymous> ([...]/third-party-resources-checker/test/mocha.js:74:39)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at maybeClose (child_process.js:743:16)
      at Process.ChildProcess._handle.onexit (child_process.js:810:5)

npm ERR! Test failed.  See above for more details.
```

### PR DESCRIPTION
**Pull request by astorije**
- Add the repository in package.json to please npm
- Fix package.json indentation
- `.gitignore` for npm packages folder
- Mention `npm install` on the readme
- Fix indentation and add missing semi-colon
- Make sure url is latest and simplify the call to url package
- Make project standalone by shipping phantomjs as a npm dependency
- Fix #3: phantomjs's exists is not callback-based (see http://phantomjs.org/api/fs/method/exists.html)

All changes on the `package.json` will make the integration with [echidna](https://github.com/w3c/echidna) easier by simply adding this as a npm dependency.

### CODE REVIEW

File: detect-phantom.js [hunk 1]
```diff
@@ -17,14 +17,12 @@ if (url === undefined) {
...
-  fs.exists(whitelist_source, function(exists) {
-    if (exists) {
-      var whitelist_content = fs.read(whitelist_source);
-      whitelisted_urls = whitelist_content.split("\n");
+    if (fs.exists(whitelist_source)) {
+        var whitelist_content = fs.read(whitelist_source);
+        whitelisted_urls = whitelist_content.split("\n");
     } else {
-      console.error("The whitelist file doesn't exist");
+        console.log("The whitelist file doesn't exist");
```
Comment (dontcallmedom) [inline detect-phantom.js]: Why have you switched from console.error to console.log?

Comment (tripu) [inline detect-phantom.js]: /me asked himself exactly the same question when he saw that line :)

Comment (astorije) [inline detect-phantom.js]: It was to check if you guys were being careful or not when reviewing :)

Or because I was confusing myself on something else, tried many many things and missed this when cleaning up my mess... You pick!

**Comment by astorije** [comment]
@dontcallmedom, after a good half night of sleep, there are parts that are missing. I'll tell you when I believe this can be merged, not ready yet.

**Comment by tripu** [comment]
Is this PR ready to review then, @astorije?

**Comment by astorije** [comment]
Hey @tripu, nah not yet, I'll get back to it when I'm done with my current task! I'll let you know.

**Comment by astorije** [comment]
@tripu, @dontcallmedom, I am done with the changes. You can review this PR and, hopefully merge it :-)
Now, the tool can be run from echidna directly by calling `third-party-resources-checker`.

I know, that's a lot of commits for a bit of code... Let me know if you want me to squash some of them before merging.

The [README](https://github.com/astorije/third-party-resources-checker/blob/astorije/fixes/README.md) now contains the output of the command when run without arguments.

**Comment by tripu** [comment]
@astorije, what I can understand&nbsp;&mdash;&nbsp;it looks good to me.
I'd let @dontcallmedom do the honours&hellip;

**Comment by dontcallmedom** [comment]
it looks good overall, and could probably be merged as is (in particular, feel free to do so if you need); I guess it's a bit weird to have the third-party-resources-checker not exposing a module interface, esp. when that interface would avoid using spawn in the test file.

Right now, when running test, the test spawns a new node process which in turns spawns a new phantom process; it would be more natural to have e.g. an exports.run method in third-party-resources-checker that would take the same parameters as the command line (I assume you would also use this from echidna/specberus)

**Comment by astorije** [comment]
@dontcallmedom, you're completely right. I got inspired by https://github.com/metaskills/mocha-phantomjs and only focused on making it a standalone process... That's awkward, I wasted some time, sorry :-(

Anyway, it is now available as a standalone program *and* as a module. Since the former was there, I didn't delete it, it might be useful someday... maybe...

**Comment by astorije** [comment]
Youhouuu! \o/
Thanks @dontcallmedom
